version: '3.8'
networks:
  serverstatus-network: { name: serverstatus-network }
x-services:
  serverstatus: &serverstatus
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options: { max-size: 10m, max-file: '3' }
    networks:
      - serverstatus-network
    restart: always

services:
  serverstatus-server:
    <<: *serverstatus
    container_name: serverstatus-server
    ports:
      - 35601:35601
    volumes:
      - ./server/config.json:/root/src/config.json
      - /etc/localtime:/etc/localtime:ro
    image: lvillis/serverstatus:server

  serverstatus-dashboard:
    <<: *serverstatus
    container_name: serverstatus-dashboard
    ports:
      - 8080:80
    environment:
      API_URL: http://127.0.0.1:35601/get
    volumes:
      - /etc/localtime:/etc/localtime:ro
    image: lvillis/serverstatus:dashboard
