name: Docker server

on:
  push:
    branches:
      - main

env:
  CONTEXT: .
  REPO_NAME: lvillis/serverstatus
  TAG_NAME: server

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        # echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ${{ env.CONTEXT }}
          file: docker/${{ env.TAG_NAME }}.Dockerfile
          push: true
          tags: ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          cache-from: type=registry,ref=${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          cache-to: type=inline